name: Build and Publish OMI

on:
  push:
    branches:
      - packer

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: 
          - CLIENT1
          - CLIENT2
        
        image-id: ["ami-321efe20"]
        os_version: ["Debian"]
        release: ["Latest"]

         

         
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip ./packer_1.7.8_linux_amd64.zip
     


    - name: Set Packer variables
      env:
        OUTSCALE_ACCESS_KEY: ${{ secrets.OUTSCALE_ACCESS_KEY}} + ${{matrix.account}}
        OUTSCALE_SECRET_KEY: ${{ secrets.OUTSCALE_SECRET_KEY}} + ${{matrix.account}}
        OUTSCALE_REGION: ${{ secrets.OUTSCALE_REGION }}
      run: |
          echo "variable \"OUTSCALE_ACCESS_KEY\" {
            default = \"${OUTSCALE_ACCESS_KEY}\"
          }" > variables.pkr.hcl
          echo "variable \"OUTSCALE_SECRET_KEY\" {
            default = \"${OUTSCALE_SECRET_KEY}\"
          }" >> variables.pkr.hcl
          echo "variable \"OUTSCALE_REGION\" {
            default = \"${OUTSCALE_REGION}\"
          }" >> variables.pkr.hcl
   
    - name: Set images variables
      run: |
        echo "variable \"image-id\" {
          default = \"${{ matrix.image-id }}\"
        }" >> variables.pkr.hcl
        echo "variable \"os_version\" {
          default = \"${{ matrix.os_version }}\"
        }" >> variables.pkr.hcl
        echo "variable \"release\" {
          default = \"${{ matrix.release }}\"
        }" >> variables.pkr.hcl

    - name: Run Packer
      run: |
        packer plugins install github.com/outscale/outscale
        packer init .
        packer validate .
        packer build .
