name: Build and Publish OMI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Outscale CLI
      run: |
        pip install osc-sdk

    - name: Set up Outscale credentials
      run: |
        mkdir -p ~/.osc
        echo "[default]" > ~/.osc/credentials
        echo "access_key = ${{ secrets.OUTSCALE_ACCESS_KEY }}" >> ~/.osc/credentials
        echo "secret_key = ${{ secrets.OUTSCALE_SECRET_KEY }}" >> ~/.osc/credentials
        echo "[default]" > ~/.osc/config.json
        echo '{ "host": "outscale", "protocol": "https", "region": "'${{ secrets.OUTSCALE_REGION }}'" }' >> ~/.osc/config.json

    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip packer_1.7.8_linux_amd64.zip
        sudo mv packer /usr/local/bin/
    
    - name: Create Packer template
      run: |
        cat <<EOF > packer-template.json
        {
          "builders": [
            {
              "type": "outscale-ebs",
              "access_key": "$${{ secrets.OUTSCALE_ACCESS_KEY }}",
              "secret_key": "$${{ secrets.OUTSCALE_SECRET_KEY }}",
              "region": "$${{ secrets.OUTSCALE_REGION }}",
              "source_ami": "ami-321efe20",
              "instance_type": "t2.micro",
              "ssh_username": "ec2-user",
              "ami_name": "patched-omi-{{timestamp}}"
            }
          ],
          "provisioners": [
            {
              "type": "shell",
              "inline": [
                "sudo mv /tmp/script.sh /opt/bootscript.sh",
                "sudo mv /tmp/setup_boot.service /usr/lib/systemd/system/setup_boot.service",
                "sudo systemctl enable setup_boot.service"
              ]
            }
          ]
        }
        EOF

    - name: Run Packer
      run: |
        packer validate packer-template.json
        packer build packer-template.json

