name: Build and Publish OMI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip ./packer_1.7.8_linux_amd64.zip
     
    - name: Set Packer variables
      run: |
        echo "variable \"OUTSCALE_ACCESS_KEY\" {
          default = \"${{ secrets.OUTSCALE_ACCESS_KEY }}\"
        }" > variables.pkr.hcl
        echo "variable \"OUTSCALE_SECRET_KEY\" {
          default = \"${{ secrets.OUTSCALE_SECRET_KEY }}\"
        }" >> variables.pkr.hcl
        echo "variable \"OUTSCALE_REGION\" {
          default = \"${{ secrets.OUTSCALE_REGION }}\"
        }" >> variables.pkr.hcl


    - name: Run Packer
      run: |
        packer plugins install github.com/outscale/outscale
        packer init .
        packer validate .
        packer build .