name: Build and Publish OMI

on:
  push:
    branches:
      - packer

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip ./packer_1.7.8_linux_amd64.zip
     
    # - name: Replace placeholders with secrets
    #   run: |
    #     #replace placeholders with secrets
    #     sed -i "s/OUTSCALE_ACCESS_KEY/${{ secrets.OUTSCALE_ACCESS_KEY }}/g" packer-template.pkr.hcl
    #     sed -i "s/OUTSCALE_SECRET_KEY/${{ secrets.OUTSCALE_SECRET_KEY }}/g" packer-template.pkr.hcl
    #     sed -i "s/OUTSCALE_REGION/${{ secrets.OUTSCALE_REGION }}/g" packer-template.pkr.hcl


    # - name: Run Packer
    #   run: |
    #     packer plugins install github.com/outscale/outscale
    #     packer init .
    #     packer validate packer-template.pkr.hcl
    #     packer build packer-template.pkr.hcl


    - name: Run Packer
      env:
        OUTSCALE_ACCESS_KEY: ${{ secrets.OUTSCALE_ACCESS_KEY }}
        OUTSCALE_SECRET_KEY: ${{ secrets.OUTSCALE_SECRET_KEY }}
        OUTSCALE_REGION: ${{ secrets.OUTSCALE_REGION }}
      run: |
        packer plugins install github.com/outscale/outscale
        packer init .
        packer validate packer-template.pkr.hcl
        packer build -var "OUTSCALE_ACCESS_KEY=${OUTSCALE_ACCESS_KEY}" \
                     -var "OUTSCALE_SECRET_KEY=${OUTSCALE_SECRET_KEY}" \
                     -var "OUTSCALE_REGION=${OUTSCALE_REGION}" \
                     packer-template.pkr.hcl