name: Build and Publish OMI

on:
  push:
    branches:
      - packer

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip packer_1.7.8_linux_amd64.zip
        sudo mv packer /usr/local/bin/
        wget https://github.com/outscale-dev/packer-plugin-outscale/releases/download/v0.0.3/packer-plugin-outscale-v0.0.3-linux-amd64.zip
        unzip packer-plugin-outscale-v0.0.3-linux-amd64.zip -d  ~/.packer.d/plugins


    - name: Set up Outscale credentials
      run: |
        mkdir -p ~/.osc
        echo "[default]" > ~/.osc/config
        echo "outscale_access_key_id = ${{ secrets.OUTSCALE_ACCESS_KEY }}" >> ~/.osc/config
        echo "outscale_secret_access_key = ${{ secrets.OUTSCALE_SECRET_KEY }}" >> ~/.osc/config
        echo "region = ${{ secrets.OUTSCALE_REGION }}" >> ~/.osc/config

    - name: Create Packer template
      run: |
        cat <<EOF > packer-template.json
        {
          "builders": [
            {
              "type": "outscale-bsu",
              "access_key": "${{ secrets.OUTSCALE_ACCESS_KEY }}",
              "secret_key": "${{ secrets.OUTSCALE_SECRET_KEY }}",
              "region": "${{ secrets.OUTSCALE_REGION }}",
              "source_ami": "ami-321efe20",
              "instance_type": "t2.micro",
              "ssh_username": "ec2-user",
              "ami_name": "patched-omi-{{timestamp}}"
            }
          ],
          "provisioners": [
            {
              "type": "shell",
              "inline": [
                "sudo mv /tmp/script.sh /opt/bootscript.sh",
                "sudo mv /tmp/setup_boot.service /usr/lib/systemd/system/setup_boot.service",
                "sudo systemctl enable setup_boot.service"
              ]
            }
          ]
        }
        EOF

    - name: Run Packer
      run: |
        packer validate packer-template.json
        packer build packer-template.json
